name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash .ci/runChecks.sh

  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
      - run: npm run test:node:mongodb
        env:
          CONNECTION_STRING: mongodb://127.0.0.1:27017/?readPreference=primary&appname=transport&ssl=false

  test-web:
    runs-on: ubuntu-latest
    container: jssoft/node_browsertests
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build:ci
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          COMMIT_HASH: ${{ github.sha }}
      - run: npm run test:web:min
